#!/bin/bash

# verbose function
Verbose(){
  >&2 echo "[$(date) xFastaMutate] $1"
}

# help message
help(){
  >&2 echo "SYNOPSIS"
  >&2 echo "    xFastaMutate <GENOME> <MUTANT> <REGION> <NAME>"
  >&2 echo ""
  >&2 echo "DESCRIPTION"
  >&2 echo "    mutate the genome with the given mutant in the region of interest"
  >&2 echo ""
  >&2 echo "OPTIONS"
  >&2 echo "    -h,--help    print help message"
  exit 0
}

# print help message if no arguments provided
if [ $# = 0 ];then help;fi

# parse command line
if [ "$1" = "-h" ];then help;fi
if [ "$1" = "--help" ];then help;fi

myrealpath='realpath -s'
if [[ $OSTYPE =~ darwin* ]];then myrealpath='grealpath -s';fi

genome=$($myrealpath $1) && shift
mutant=$($myrealpath $1) && shift
roi=$1 && shift
name=$1

# run the internal routine
$BIOINFO_TOOL_XGSUTILS/faxutils/mutate_subseq $genome $mutant $roi $name 
